# Generated by Django 4.0.1 on 2022-06-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='uncategorised', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.CharField(max_length=400),
        ),
    ]
