# Generated by Django 4.0.1 on 2022-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_newsstory_category_alter_newsstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='Cakes', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
